"""
RCA LLM client — generates polished reasoning text from structured findings.

CRITICAL: This client NEVER determines root causes. It only rephrases
existing reasoning text generated by the deterministic rule engine.
The LLM is used purely as a text refinement tool.
"""

import json

import httpx
from anthropic import AsyncAnthropic, APIError as AnthropicAPIError
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type

from app.core.config import get_settings
from app.core.logging_config import get_logger
from app.models.rca import RcaFinding, RcaRequest
from app.services.rca_prompt_builder import build_rca_reasoning_prompt, build_rca_summary_prompt

logger = get_logger(__name__)


class RcaLlmClient:
    """
    Optionally refines RCA reasoning text using an LLM. If the LLM is
    unavailable, the original deterministic reasoning is returned unchanged.
    """

    def __init__(self):
        self._settings = get_settings()

    async def refine_reasoning(
        self, request: RcaRequest, finding: RcaFinding
    ) -> str:
        prompt = build_rca_reasoning_prompt(request, finding)

        try:
            if self._settings.llm_provider == "claude":
                return await self._call_claude(prompt)
            return await self._call_ollama(prompt)
        except Exception as exc:
            logger.warning(
                "rca_llm_refinement_failed",
                provider=self._settings.llm_provider,
                bottleneck=finding.bottleneck_type.value,
                error=str(exc),
            )
            return finding.reasoning

    async def generate_summary(
        self, request: RcaRequest, findings: list[RcaFinding]
    ) -> str:
        prompt = build_rca_summary_prompt(request, findings)

        try:
            if self._settings.llm_provider == "claude":
                return await self._call_claude(prompt)
            return await self._call_ollama(prompt)
        except Exception as exc:
            logger.warning(
                "rca_llm_summary_failed",
                provider=self._settings.llm_provider,
                error=str(exc),
            )
            return self._fallback_summary(request, findings)

    # ── Ollama backend ─────────────────────────────────────────

    @retry(
        stop=stop_after_attempt(2),
        wait=wait_exponential(multiplier=1, min=1, max=4),
        retry=retry_if_exception_type(httpx.TransportError),
        reraise=True,
    )
    async def _call_ollama(self, prompt: str) -> str:
        async with httpx.AsyncClient(timeout=self._settings.llm_timeout_seconds) as client:
            response = await client.post(
                f"{self._settings.ollama_base_url}/api/generate",
                json={
                    "model": self._settings.ollama_model,
                    "prompt": prompt,
                    "stream": False,
                    "options": {"temperature": 0.2, "num_predict": 200},
                },
            )
            response.raise_for_status()
            data = response.json()
            return data.get("response", "").strip()

    # ── Claude backend ──────────────────────────────────────────

    @retry(
        stop=stop_after_attempt(2),
        wait=wait_exponential(multiplier=1, min=1, max=4),
        retry=retry_if_exception_type(AnthropicAPIError),
        reraise=True,
    )
    async def _call_claude(self, prompt: str) -> str:
        if not self._settings.anthropic_api_key:
            raise ValueError("ANTHROPIC_API_KEY is not configured")

        client = AsyncAnthropic(api_key=self._settings.anthropic_api_key)
        response = await client.messages.create(
            model=self._settings.anthropic_model,
            max_tokens=250,
            temperature=0.2,
            messages=[{"role": "user", "content": prompt}],
        )
        return "".join(
            block.text for block in response.content if block.type == "text"
        ).strip()

    # ── Fallback ────────────────────────────────────────────────

    def _fallback_summary(
        self, request: RcaRequest, findings: list[RcaFinding]
    ) -> str:
        if not findings:
            return f"No bottlenecks detected for {request.service_name}."

        primary = findings[0]
        return (
            f"Root cause analysis for {request.service_name} identified "
            f"{primary.bottleneck_type.value.lower().replace('_', ' ')} as the "
            f"primary bottleneck (confidence: {primary.confidence:.0%}). "
            f"{primary.reasoning}"
        )
