package com.analyzer.modules.recommendation.model;

public enum RecommendationSource {
    AI_MODEL,   // parsed from FastAPI rawRecommendations JSON
    RULE_BASED  // generated by Java threshold analysis
}
