package com.analyzer.backend.modules.logging.model;

import com.analyzer.backend.infrastructure.database.JsonMapConverter;
import com.analyzer.backend.modules.simulation.model.Simulation;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.util.Map;

@Entity
@Table(
        name = "log_entries",
        indexes = {
                @Index(name = "idx_log_simulation_id",
                        columnList = "simulation_id"),
                @Index(name = "idx_log_level",
                        columnList = "level"),
                @Index(name = "idx_log_category",
                        columnList = "category"),
                @Index(name = "idx_log_service_occurred",
                        columnList = "service_name, occurred_at DESC"),
                @Index(name = "idx_log_sim_level",
                        columnList = "simulation_id, level"),
                @Index(name = "idx_log_occurred_at",
                        columnList = "occurred_at DESC")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class LogEntry {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Nullable — system-level logs are not tied to a simulation.
     * All logs generated by LogProcessor will always have a simulationId.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "simulation_id")
    private Simulation simulation;

    @Column(name = "simulation_id", insertable = false, updatable = false)
    private Long simulationId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    private LogLevel level;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private LogCategory category;

    /** The microservice being analysed — mirrors simulation.targetService. */
    @Column(nullable = false, length = 100)
    private String serviceName;

    /** The Spring component that generated this log entry. */
    @Column(nullable = false, length = 100)
    private String source;

    @Column(nullable = false, columnDefinition = "TEXT")
    private String message;

    /**
     * Structured context — serialised to JSON by JsonMapConverter.
     * Contains metric values, threshold comparisons, and event metadata.
     */
    @Convert(converter = JsonMapConverter.class)
    @Column(columnDefinition = "TEXT")
    private Map<String, Object> context;

    /** Populated only for ERROR / FATAL entries that caught an exception. */
    @Column(columnDefinition = "TEXT")
    private String stackTrace;

    /** Wall-clock duration for PERFORMANCE category entries, in milliseconds. */
    @Column(name = "duration_ms")
    private Long durationMs;

    @Column(nullable = false)
    private Instant occurredAt;

    @CreationTimestamp
    @Column(updatable = false)
    private Instant createdAt;

    // ── Domain helpers =>

    public boolean isError() {
        return level == LogLevel.ERROR || level == LogLevel.FATAL;
    }

    public boolean isWarning() {
        return level == LogLevel.WARN;
    }

    public boolean isProblematic() {
        return level.isAtLeast(LogLevel.WARN);
    }

    public boolean hasContext() {
        return context != null && !context.isEmpty();
    }
}